// Run with Playwright installed: node tests/browser.test.cjs
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const root = path.resolve(__dirname, '..');
const errors = [];
const server = http.createServer((req, res) => {
  const file = req.url.split('?')[0] === '/wallet-validation.js' ? 'wallet-validation.js' : 'index.html';
  res.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript; charset=utf-8' : 'text/html; charset=utf-8');
  res.end(fs.readFileSync(path.join(root, file)));
});
const visible = async (page, selector) => assert.equal(await page.locator(selector).isVisible(), true, selector);
const close = async page => { await page.keyboard.press('Escape'); };
async function swipe(page, selector, dir = 1, touch = false) {
  const rect = await page.locator(selector).boundingBox();
  const y = rect.y + Math.min(rect.height / 2, 120), x = rect.x + rect.width * (dir === 1 ? .8 : .2), end = x - dir * rect.width * .6;
  if (touch) {
    const session = await page.context().newCDPSession(page);
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] });
    for (let i = 1; i <= 6; i++) await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + (end - x) * i / 6, y }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await session.detach();
  } else {
    await page.mouse.move(x, y); await page.mouse.down(); await page.mouse.move(end, y, { steps: 8 }); await page.mouse.up();
  }
  // The app suppresses the click generated by a swipe for 400ms.
  await page.waitForTimeout(450);
}
async function add(page, name, number, type = 'membership') {
  await page.locator('[data-open="add"]').click();
  await page.locator(`#addSeg [data-v="${type}"]`).click();
  await page.locator('#addName').fill(name); await page.locator('#addCode').fill(number);
  await page.locator('#addForm [type="submit"]').click();
}
(async () => {
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const url = `http://127.0.0.1:${server.address().port}/`;
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe' });
  try {
    for (const width of [390, 320]) {
      const context = await browser.newContext({ viewport: { width, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce', colorScheme: 'dark' });
      const page = await context.newPage();
      page.on('pageerror', e => errors.push(e.message));
      await page.route('https://fonts.googleapis.com/**', route => route.abort());
      await page.goto(url);
      await visible(page, '#v-home');
      await page.locator('.detect-card h3').click();
      assert.equal(await page.locator('#flow').evaluate(el => el.classList.contains('on')), false);
      await page.locator('#btrack').scrollIntoViewIfNeeded(); await swipe(page, '#btrack', 1, true);
      assert.match(await page.locator('#bcount').innerText(), /2 \/ 3/); await visible(page, '#v-home');
      await swipe(page, '.views', 1, true); await visible(page, '#v-history');
      await swipe(page, '#histList', 1, true);
      assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'done');
      assert.equal(await page.locator('#histList .tx').count(), 4);
      await swipe(page, '#chips', 1); assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'pending');
      await swipe(page, '#histList', 1, true); assert.equal(await page.locator('#histList .tx').count(), 1);
      await swipe(page, '#histList', 1, true); assert.equal(await page.locator('#chips .on').getAttribute('data-f'), 'missed');
      await swipe(page, '.tabbar', 1, true); await visible(page, '#v-stats');
      await page.locator('#cats [data-category="dine"]').click();
      assert.match(await page.locator('#detailBody').innerText(), /빕스.*|11,100/); await close(page);
      await page.locator('#rank [data-benefit="kb"]').click();
      assert.equal(await page.locator('#detailBody [data-transaction]').count(), 2);
      await page.locator('#detailBody [data-transaction]').first().click();
      assert.match(await page.locator('#detailBody').innerText(), /리캐치 성공 수수료/); await close(page);
      await page.locator('[data-insight="success"]').click(); assert.match(await page.locator('#detailBody').innerText(), /완료 4건/); await close(page);
      await page.locator('#trend [data-month="0"]').click(); assert.match(await page.locator('#detailBody').innerText(), /개별 결제 데이터/); await close(page);
      await swipe(page, '.tabbar', 1); await visible(page, '#v-wallet');
      assert.equal(await page.locator('#memList .mem').count(), 3);
      assert.equal(await page.locator('#memMore').isVisible(), false);
      await page.locator('#memList [data-m="0"]').click(); await swipe(page, '#passRail', 1, true);
      assert.match(await page.locator('#passIdx').innerText(), /2 \/ 3/);
      await swipe(page, '#passRail', -1); assert.match(await page.locator('#passIdx').innerText(), /1 \/ 3/); await close(page);
      await page.locator('#facts [data-condition="student"]').click();
      assert.match(await page.locator('#conditionReason').innerText(), /예시 프로필/);
      await page.locator('#conditionValue').selectOption({ label: '대학원생' }); await page.locator('#conditionForm [type="submit"]').click();
      assert.match(await page.locator('#facts').innerText(), /대학원생/);
      await page.reload(); await visible(page, '#v-wallet'); assert.match(await page.locator('#facts').innerText(), /대학원생/);
      await page.locator('#facts [data-condition="region"]').click();
      await page.locator('#conditionValue').selectOption({ label: '기타 지역' }); await page.locator('#conditionCustom').fill('수원시');
      await page.locator('#conditionForm [type="submit"]').click(); assert.match(await page.locator('#facts').innerText(), /수원시/);
      await add(page, '테스트', ''); assert.match(await page.locator('#addError').innerText(), /입력/);
      await page.locator('#addCode').fill('12345678abc'); await page.locator('#addForm [type="submit"]').click(); assert.match(await page.locator('#addError').innerText(), /숫자만/);
      await page.locator('#addCode').fill('7700-1923-8832-1049'); await page.locator('#addForm [type="submit"]').click(); assert.match(await page.locator('#addError').innerText(), /이미 지갑/); await close(page);
      await add(page, '<img src=x onerror=alert(1)>', '1234 5678 9012');
      await page.waitForFunction(() => !document.querySelector('#sh-add').classList.contains('on'));
      assert.equal(await page.locator('#memList .mem').count(), 3); await visible(page, '#memMore');
      await page.locator('#memMore').click(); assert.equal(await page.locator('#collectionBody .mem').count(), 4);
      assert.equal(await page.locator('#collectionBody img').count(), 0);
      if (width === 390 && process.env.QA_OUTPUT) { fs.mkdirSync(process.env.QA_OUTPUT, { recursive: true }); await page.screenshot({ path: path.join(process.env.QA_OUTPUT, 'membership-all-dark.png') }); }
      await page.locator('#collectionBody [data-m="3"]').click(); assert.equal(await page.locator('#passRail .pass').count(), 4);
      assert.match(await page.locator('#passIdx').innerText(), /4 \/ 4/); await close(page);
      await add(page, '추가 카드', '2345678901234567', 'card');
      await page.waitForFunction(() => !document.querySelector('#sh-add').classList.contains('on'));
      assert.equal(await page.locator('#cardRail .ccard').count(), 3); await page.locator('#cardsMore').click();
      assert.equal(await page.locator('#collectionBody [data-card-detail]').count(), 4);
      await page.locator('#collectionBody [data-card-detail="3"]').click(); await page.locator('[data-card-code="3"]').click(); await visible(page, '#sh-code'); await close(page);
      // Server adapter: same normalized failed number is blocked without a second call, even after reload.
      await page.evaluate(() => { window.calls = 0; window.RecatchMembershipAPI = { validate: async () => { window.calls++; return { ok: false, code: 'NOT_FOUND' }; } }; });
      await add(page, '실패 번호', '345678901234'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('찾을 수'));
      await page.locator('#addCode').fill('3456-7890-1234'); await page.locator('#addForm [type="submit"]').click();
      await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('다시 요청하지'));
      assert.equal(await page.evaluate(() => window.calls), 1); await close(page);
      await page.reload(); await page.evaluate(() => { window.calls = 0; window.RecatchMembershipAPI = { validate: async () => { window.calls++; return { ok: true }; } }; });
      await add(page, '동일 실패 번호', '345678901234'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('다시 요청하지'));
      assert.equal(await page.evaluate(() => window.calls), 0); await close(page);
      await page.evaluate(() => { window.RecatchMembershipAPI = { validate: async () => { window.calls++; throw Error('network'); } }; });
      await add(page, '네트워크', '456789012345'); await page.waitForFunction(() => document.querySelector('#addError').textContent.includes('연결 문제'));
      await page.locator('#addForm [type="submit"]').click(); await page.waitForFunction(() => window.calls === 2); await close(page);
      // Existing cards, membership rails and demo outcome paths remain usable.
      await page.locator('#cardRail').scrollIntoViewIfNeeded();
      await swipe(page, '#cardRail', 1, true); assert.match(await page.locator('#cardMeta').innerText(), /Mr.Life/); await visible(page, '#v-wallet');
      const before = await page.locator('#v-wallet').evaluate(el => el.scrollTop);
      const rect = await page.locator('.views').boundingBox(), touchSession = await context.newCDPSession(page);
      await touchSession.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: width / 2, y: rect.y + 500 }] });
      for (let i = 1; i <= 6; i++) await touchSession.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: width / 2, y: rect.y + 500 - i * 30 }] });
      await touchSession.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await touchSession.detach();
      await page.waitForTimeout(100); assert.ok(await page.locator('#v-wallet').evaluate(el => el.scrollTop) > before); await visible(page, '#v-wallet');
      await page.locator('.tabbar [data-tab="home"]').click(); await page.locator('#simCard').click();
      await page.locator('#rcNoti').click(); await page.locator('#pyOk').click(); await page.locator('#dnOk').click();
      assert.equal(await page.locator('#heroCount').innerText(), '5');
      await page.locator('#simCard').click(); await page.locator('#rcNoti').click(); await page.locator('#pySkip').click();
      await page.locator('.tabbar [data-tab="history"]').click(); await page.locator('#chips [data-f="missed"]').click(); assert.equal(await page.locator('#histList .tx').count(), 2);
      await page.locator('.tabbar [data-tab="wallet"]').click();
      if (width === 390) {
        const output = process.env.QA_OUTPUT;
        if (output) { fs.mkdirSync(output, { recursive: true }); await page.screenshot({ path: path.join(output, 'wallet-dark.png') }); }
      }
      assert.equal(await page.evaluate(() => document.querySelector('.app').scrollWidth <= document.querySelector('.app').clientWidth), true);
      await context.close();
      console.log(`PASS: ${width}px, touch/mouse gestures, details, overflow, validation/cache, conditions, demo regression`);
    }
    // Extra source categories and benefits keep the original 4/3 previews and expose all items.
    const page = await browser.newPage({ viewport: { width: 390, height: 844 }, reducedMotion: 'reduce' });
    page.on('pageerror', e => errors.push(e.message));
    await page.route('**/', route => route.fulfill({ contentType: 'text/html', body: fs.readFileSync(path.join(root, 'index.html'), 'utf8').replace("srcKey:'cj',status:'pending'", "srcKey:'cj',status:'done'").replace("id:6,store:'맘스터치 영남대점',cat:'dine'", "id:6,store:'맘스터치 영남대점',cat:'bake'").replace("srcKey:'skt',status:'missed'", "srcKey:'skt',status:'done'") }));
    await page.goto(url); await page.locator('.tabbar [data-tab="stats"]').click();
    assert.equal(await page.locator('#cats .cat').count(), 4); assert.equal(await page.locator('#rank .rank').count(), 3);
    await page.locator('#catsMore').click(); assert.equal(await page.locator('#collectionBody [data-category]').count(), 6); await close(page);
    await page.locator('#rankMore').click(); assert.equal(await page.locator('#collectionBody [data-benefit]').count(), 4); await close(page);
    const output = process.env.QA_OUTPUT;
    if (output) { await page.screenshot({ path: path.join(output, 'stats-light.png') }); await page.locator('#cats .cat').first().click(); await page.screenshot({ path: path.join(output, 'detail-light.png') }); }
    assert.deepEqual(errors, []);
    console.log('PASS: overflow fixtures and zero browser runtime errors');
  } finally { await browser.close(); server.close(); }
})().catch(error => { console.error(error); server.close(); process.exitCode = 1; });
